#python experiments.py --model=simple-cnn \
#--dataset=mnist \
#--alg=fedavg \
#--lr=0.01 \
#--batch-size=64 \
#--epochs=10 \
#--n_parties=10 \
#--rho=0.9 \
#--comm_round=50 \
#--partition=homo \
#--beta=0.5 \
#--device='cuda:0' \
#--datadir='./data/' \
#--logdir='./logs/' \
#--noise=0.1 \
#--init_seed=0
python experiments.py --model=simple-cnn \
--dataset=mnist \
--alg=fedavg \
--lr=0.01 \
--batch-size=64 \
--epochs=10 \
--n_parties=2 \
--rho=0.9 \
--comm_round=1 \
--partition=homo \
--beta=0.5 \
--device='cpu' \
--datadir='./data/' \
--logdir='./logs/' \
--noise=0.1 \
--init_seed=0